### PR TITLE
Add addon status badge

### PR DESCRIPTION
**Pull request by lubien**
I'm proposing a badge pattern for Tree of Savior addons.
Using these badges, users can easily understand that the system they are using is approved / is safe / have a unknown status / is unsafe.
Read more at [Awesome ToS #addons-badges](https://github.com/lubien/awesome-tos#addons-badges).
Hope you like the idea.

### CODE REVIEW

**Comment by fiote** [comment]
I liked it! I'm using them on my repository!

**Comment by lubien** [comment]
@fiote I was just preparing to make a PR to you too! Awesome!

**Comment by fiote** [comment]
@lubien I'm following all addon-repositories so I read all the comments/issues lol.

**Comment by lubien** [comment]
@fiote I should do it too.

**Comment by Lemon-King** [comment]
Looks good, I do need to update my README.md anyhow.

**Pull request merged**
